### ISSUE TITLE
LDAP as optional

### ISSUE THREAD

**Issue by imonteiro** [nitecon/zfcuser-ldap#4]
Hi,

First, thanks to make this module avaiable for everyone.

The goal is give the possibility to login without LDAP (choosen at login form or based on extra variable stored at database), using ZfcUser. It's possible?

Thanks in advance.

**Comment by nitecon** [comment]
ZfcUser uses whats called a chain adapter, it cycles through all of the "available" adapters to see if a user is authenticated.  In the original ver 1.\* fo zfcuserldap you had to set only a single adapter for zfcuser which is the ldap one.  I'm working on the new release that will allow you to run multiple adapters however I'm not quite done yet as documentation is lacking on it.  Currently zfcuser doesn't support a choice of adapters for it's login form and until that changes my "plugin" module cannot support that :(

**Comment by imonteiro** [comment]
Thanks.

I will try the master branch :)

Regarding the login form... it's possible to have one login form for each adapter?

**Comment by nitecon** [comment]
Currently i don't believe you can do that under zfcuser.  I'm having the same issue with some of my applications and due to that I'm busy writing my own authentication system with multiple providers (idauth) although it's still pretty far away from being usable.  You may want to ask the question to the zfcuser team whether it is possible.
